### PR TITLE
Doc

### LINKED ISSUE #11: README should be updated and in part moved to card-game
As the title says, the README should be updated with the changes regarding the split and part of it should go to doner-kebard/card-game.

### PR DESCRIPTION
**Pull request by Masclins**
**Description**

README is updated to represent the split of projects.

**Issues Resolved**

Resolves #11 

**Hotspots**

Probably in `CONTRIBUTING.md` **Usage** should be updated to include whatever is needed regarding Redis. I think something needs to be done with that to make the backend work.

### CODE REVIEW

**Comment by kenan-rhoton** [comment]
Redis is being killed with fire, I would wait until that's done before updating it in the CONTRIBUTING guide :upside_down_face:

**Comment by Masclins** [comment]
@kenan-rhoton I'm now waiting for you to update it as you feel appropiate, regarding the new persistence system.

**Comment by kenan-rhoton** [comment]
On it!

**Comment by Masclins** [comment]
Great. IMHO it's ready to be merged.

**Review by kenan-rhoton — APPROVED** [review]
Needs more tests! (Just kidding)

**Pull request merged**
